preliminary script to write spi flash

diff --git a/arduino/tools/openocd/scripts/program_flash b/arduino/tools/openocd/scripts/program_flash
--- a/arduino/tools/openocd/scripts/program_flash
+++ b/arduino/tools/openocd/scripts/program_flash
@@ -37,6 +37,18 @@ OPENOCD_WAIT_TO_READY=360  # 6 minutes
 GDB_WAIT_TO_KILL=960    # 16 minutes
 GDB_WAIT_TO_READY=900   # 15 minutes
 
+
+# flash configuration, make sure this configuration align with
+# helper program configuration, and the spi flash
+SPI_FLASH_SECTOR_SIZE_BYTES=4096 # (4 * 1024)
+
+# make sure to have same setting with flash reader
+SPI_FLASH_VERIFY_READ_BLOCK_SIZE_BYTES=256
+
+# size of report variable
+REPORT_SIZE=384
+
+
 # function to conveniently kill all process and recursive subprocess
 killallsubprocess() {
 	l_all_process_with_selected_parent="$(ps -o "ppid=" -o "pid=" | grep "^[[:blank:]]*$1[[:blank:]]")"
@@ -167,7 +179,7 @@ export THIS_SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
 # is this easy target for path traversal attack?
 # is this can lead to security threat/vulnerability?
 RESOLVED_PATH="$(cd "$1" && pwd)"
-export PATH="$PATH:$1"
+export PATH="$PATH:$RESOLVED_PATH"
 
 # to communicate with openocd, we will use pipe
 # the idea is to create named pipe, it is ok if this pipe
@@ -316,26 +328,239 @@ fi
 # reset and halt cpu before gdb connected
 (sleep 1 && echo "reset halt" && echo && sleep 1 && echo "exit" && echo && sleep 1) | telnet "$OPENOCD_HOST" "$OPENOCD_PORT_TELNET"
 
-# create gdb script (need mktemp command)
-GDB_SCRIPT="$(mktemp)"
 
-cat > "$GDB_SCRIPT" <<EOF
+# create gdbinit file up front, we will reuse this file for the whole process
+# FIXME: in here, we assume mktemp success but it not always the case, please handle if mktemp failed too
+GDBINIT="$(mktemp)"
+
+
+# ##################################################
+# ok, openocd ready, soc already reset too
+#
+# probe spi flash
+
+# create report file
+# FIXME: add handling for failed mktemp
+FLASH_PROBE_REPORT="$(mktemp)"
+
+# build gdb init
+cat >> "$GDBINIT" <<EOF
 target extended-remote $OPENOCD_HOST:$OPENOCD_PORT_GDB
 monitor reset halt
 load
-monitor resume
-#monitor shutdown
-disconnect
-#detach
+break INTERRUPT_HERE_TO_GET_REPORT
+continue
+disable breakpoints 1
+dump memory $FLASH_PROBE_REPORT report report+$REPORT_SIZE
 quit
 EOF
 
+# run helper spi_flash_probe with gdb
+RETVAL=0
+timeout -s "INT" -k "$GDB_WAIT_TO_KILL" "$GDB_WAIT_TO_READY" riscv32-unknown-elf-gdb --command="$GDBINIT" "$THIS_SCRIPT_DIR/spi_flash_probe/build/spi_flash_probe/spi_flash_probe" || RETVAL="$?" || true
+
+# check if gdb return ok
+if [ "$RETVAL" -ne "0" ] ; then
+	echo "looks like gdb is hang"
+
+	echo "clean up openocd subprocess..."
+
+	export SUBPROCESS_PIDS_FILES="$(mktemp)"
+	#kill "$OPENOCD_PID" || true
+	killallsubprocess "$OPENOCD_PID" || true
+
+	# try to kill subprocess that not killed
+	sleep 2 # give a little bit time to subprocess to respond to SIGTERM
+	killprocesslistedin "$SUBPROCESS_PIDS_FILES"
+
+	# remove subprocess list
+	rm -v "$SUBPROCESS_PIDS_FILES" "$GDBINIT" "$FLASH_PROBE_REPORT"
+
+	RETVAL=0
+	wait "$OPENOCD_PID" || RETVAL="$?" || true
+
+	# exit with openocd return code
+	#exit "$RETVAL"
+	exit 2
+fi
+
+
+# check FLASH_PROBE_REPORT
+END_OF_REPORT_LINE="$( (grep -a -n "^END OF REPORT\$" "$FLASH_PROBE_REPORT" | sed -e "s/\\([0-9]\\+\\):END OF REPORT/\\1/g") || true )"
+if [ -z "$END_OF_REPORT_LINE" ] ; then
+	# looks like flash is not found
+	# clean-up and exit failed
+	echo "ERROR: flash probe report don't have \"END OF REPORT\" line"
+	echo "ERROR: spi flash probably don't attached or not responding to SFDP command"
+
+	# clean up!
+
+	# shutdown gdb server
+	(sleep 1 && echo "shutdown" && echo && sleep 1) | telnet "$OPENOCD_HOST" "$OPENOCD_PORT_TELNET"
+
+	# #########################
+	# wait openocd exit
+
+	# openocd should return ok here
+	RETVAL=0
+	wait "$OPENOCD_PID" || RETVAL="$?" || true
+
+	# inform upload process is finished
+	echo "openocd (PID: $OPENOCD_PID) exit with return value $RETVAL"
+
+	# delete gdbinit and flash report
+	rm -v "$GDBINIT" "$FLASH_PROBE_REPORT"
+
+	# exit failed
+	exit 1
+fi
+
+# truncate report so that we don't have to use grep -a again and again
+TRUNCATE_TO="$(head -n "$END_OF_REPORT_LINE" "$FLASH_PROBE_REPORT" | wc -c)"
+
+# use dd to truncate instead of truncate, because truncate is not posix command
+dd if="/dev/null" of="$FLASH_PROBE_REPORT" bs=1 count=0 seek="$TRUNCATE_TO"
+
+# print flash info
+cat "$FLASH_PROBE_REPORT"
+
+# check if flash exist
+SPI_FLASH_FOUND="$(grep "^FLASH FOUND\$" "$FLASH_PROBE_REPORT")"
+if [ -z "$SPI_FLASH_FOUND" -o "$SPI_FLASH_FOUND" != "FLASH FOUND" ] ; then
+	# flash is not found
+
+	# clean-up and exit failed
+	echo "ERROR: flash probe report don't have \"FLASH FOUND\" line"
+	echo "ERROR: spi flash probably don't attached or not responding to SFDP command"
+
+	# clean up!
+
+	# shutdown gdb server
+	(sleep 1 && echo "shutdown" && echo && sleep 1) | telnet "$OPENOCD_HOST" "$OPENOCD_PORT_TELNET"
+
+	# #########################
+	# wait openocd exit
+
+	# openocd should return ok here
+	RETVAL=0
+	wait "$OPENOCD_PID" || RETVAL="$?" || true
+
+	# inform upload process is finished
+	echo "openocd (PID: $OPENOCD_PID) exit with return value $RETVAL"
+
+	# delete gdbinit and flash report
+	rm -v "$GDBINIT" "$FLASH_PROBE_REPORT"
+
+	# exit failed
+	exit 1
+fi
+
+# check spi flash size
+HAS_SPI_FLASH_SIZE_BIT=1
+SPI_FLASH_SIZE_BIT="$(grep "^FLASH DENSITY BIT: ==" "$FLASH_PROBE_REPORT" | sed -e "s/^FLASH DENSITY BIT[^0-9]\\+\\([0-9]\\+\\)\$/\\1/g")"
+if [ -z "$SPI_FLASH_SIZE_BIT" ] ; then
+	HAS_SPI_FLASH_SIZE_BIT=0
+fi
+
+# generate pulpisimmo executable
+PULPISIMMO_EXECUTABLE="$(mktemp)"
+
+"$THIS_SCRIPT_DIR/elf_to_flash_image" "$4" "$PULPISIMMO_EXECUTABLE"
+
+# is input file will fit into flash?
+EXECUTABLE_SIZE="$(wc -c "$PULPISIMMO_EXECUTABLE" | sed -e "s/^\\([0-9]\\+\\)[[:blank:]]\\+.*\$/\\1/g")"
+
+if [ "$HAS_SPI_FLASH_SIZE_BIT" -ne "0" -a "$EXECUTABLE_SIZE" -ge "$((SPI_FLASH_SIZE_BIT / 8))" ] ; then
+	# executable is larger than flash size
+
+	# clean-up and exit failed
+	echo "ERROR: executable is larger than flash size"
+
+	# clean up!
+
+	# shutdown gdb server
+	(sleep 1 && echo "shutdown" && echo && sleep 1) | telnet "$OPENOCD_HOST" "$OPENOCD_PORT_TELNET"
+
+	# #########################
+	# wait openocd exit
+
+	# openocd should return ok here
+	RETVAL=0
+	wait "$OPENOCD_PID" || RETVAL="$?" || true
+
+	# inform upload process is finished
+	echo "openocd (PID: $OPENOCD_PID) exit with return value $RETVAL"
+
+	# delete gdbinit and flash report
+	rm -v "$PULPISIMMO_EXECUTABLE" "$GDBINIT" "$FLASH_PROBE_REPORT"
+
+	# exit failed
+	exit 1
+fi
+
+# remove flash probe report
+rm -v "$FLASH_PROBE_REPORT"
+
+
+# ##################################################
+# ok, flash is ready
+# prepare to flashing by generating splice file and new gdbinit
+
+# truncate gdbinit (with dd)
+dd if="/dev/null" of="$GDBINIT" count=0 seek=0
+
+# create splice list file
+LIST_SPLIT_FILE="$(mktemp)"
+
+# add gdb init prologue
+cat >> "$GDBINIT" <<EOF
+target extended-remote $OPENOCD_HOST:$OPENOCD_PORT_GDB
+monitor reset halt
+load
+break INTERRUPT_HERE_TO_OVERWRITE_DATA_TO_SEND_TO_FLASH
+continue
+EOF
+
+# loop create splited file
+i=0
+LAST_SEGMENT_SIZE=0 # set last segment tovalue different from SPI_FLASH_SECTOR_SIZE_BYTES
+while [ "$((i * SPI_FLASH_SECTOR_SIZE_BYTES))" -lt "$EXECUTABLE_SIZE" ] ; do
+	# create segment file
+	SEGMENT_FILE="$(mktemp)"
+
+	# copy segment
+	dd bs="$SPI_FLASH_SECTOR_SIZE_BYTES" count="1" if="$PULPISIMMO_EXECUTABLE" of="$SEGMENT_FILE" skip="$i" conv="nocreat,notrunc"
+
+	# append segment file to LIST_SPLIT_FILE
+	echo "$SEGMENT_FILE" >> "$LIST_SPLIT_FILE"
+
+	# record last segment size
+	# this is also the length of actual copied data
+	LAST_SEGMENT_SIZE="$(wc -c "$SEGMENT_FILE" | sed -e "s/^\\([0-9]\\+\\)[[:blank:]]\\+.*\$/\\1/g")"
+
+# add to gdbinit
+cat >> "$GDBINIT" <<EOF
+restore $SEGMENT_FILE binary buffer
+set *buffer_fill_length=$LAST_SEGMENT_SIZE
+continue
+EOF
+
+	# increment i
+	i="$((i + 1))"
+done
+
+# add gdb init epilogue
+cat >> "$GDBINIT" <<EOF
+quit
+EOF
+
+
 # upload with gdb
 RETVAL=0
-timeout -s "INT" -k "$GDB_WAIT_TO_KILL" "$GDB_WAIT_TO_READY" riscv32-unknown-elf-gdb --command="$GDB_SCRIPT" "$4" || RETVAL="$?" || true
+timeout -s "INT" -k "$GDB_WAIT_TO_KILL" "$GDB_WAIT_TO_READY" riscv32-unknown-elf-gdb --command="$GDBINIT" "$THIS_SCRIPT_DIR/spi_flash_writer/build/spi_flash_writer/spi_flash_writer" || RETVAL="$?" || true
 
 # remove temporary file
-rm -v "$GDB_SCRIPT"
+rm -v "$GDBINIT"
 
 # check if gdb return ok
 if [ "$RETVAL" -ne "0" ] ; then
@@ -357,10 +582,31 @@ if [ "$RETVAL" -ne "0" ] ; then
 	RETVAL=0
 	wait "$OPENOCD_PID" || RETVAL="$?" || true
 
+	while IFS= read -r line ; do
+		rm -v "$line"
+	done < "$LIST_SPLIT_FILE"
+
+	# remove list file and merge file
+	rm -v "$PULPISIMMO_EXECUTABLE" "$LIST_SPLIT_FILE"
+
 	# exit with openocd return code
 	#exit "$RETVAL"
 	exit 2
 fi
+
+
+# ##################################################
+# TODO: verify flash
+
+
+
+
+
+
+
+
+
+
 
 # shutdown gdb server
 (sleep 1 && echo "shutdown" && echo && sleep 1) | telnet "$OPENOCD_HOST" "$OPENOCD_PORT_TELNET"
@@ -371,6 +617,12 @@ fi
 # openocd should return ok here
 RETVAL=0
 wait "$OPENOCD_PID" || RETVAL="$?" || true
+
+while IFS= read -r line ; do
+	rm -v "$line"
+done < "$LIST_SPLIT_FILE"
+
+rm -v "$PULPISIMMO_EXECUTABLE" "$LIST_SPLIT_FILE"
 
 # inform upload process is finished
 echo "openocd (PID: $OPENOCD_PID) exit with return value $RETVAL, upload is finished!"
